### ISSUE TITLE
 The link of video demo is invalid

### ISSUE THREAD

**Issue by Echo-jyt** [sstzal/DiffTalk#33]
The link of video demo is invalid
![image](https://github.com/user-attachments/assets/527da578-a7e0-4c81-a916-bdfdd4dcf710)

**Comment by sstzal** [comment]
Here is the video link on Youtube : https://youtu.be/tup5kbsOJXc

**Comment by Echo-jyt** [comment]
> Here is the video link on Youtube : https://youtu.be/tup5kbsOJXc
thanks very much!
