### ISSUE TITLE
The link of the model is invaild

### ISSUE THREAD

**Issue by Echo-jyt** [sstzal/DiffTalk#34]
![image](https://github.com/user-attachments/assets/74448492-4ad0-45d3-94c2-2032b35963ca)
Hi, thanks for your great work! But The link of the model is invaild.

**Comment by VictorLeeICT** [comment]
+1

**Comment by Echo-jyt** [comment]
> +1

Hi, have you solved it?

**Comment by Echo-jyt** [comment]
It is: https://ommer-lab.com/files/latent-diffusion/vq-f4.zip
