### ISSUE TITLE
About DeepSpeechRNN

### ISSUE THREAD

**Issue by HUAFOR** [sstzal/DiffTalk#9]
您原文提到了使用了该模型，但是您项目代码中没有用到这一模型，想请教您这个模型是否是在预处理的程序中引用？
 
![image](https://github.com/sstzal/DiffTalk/assets/58834906/7c638917-ba7e-4ac6-827a-00e7ef034421)

**Comment by wwqy** [comment]
您好，请问您复现的时候数据部分的data.txt是怎么处理的呢

**Comment by MengShen0709** [comment]
Hi, I found one github repos that might help reproduce DeepSpeech feature extraction.
https://github.com/YudongGuo/AD-NeRF/blob/master/data_util/deepspeech_features/extract_ds_features.py

**Comment by sstzal** [comment]
是的，我们在数据处理部分沿用了AD-NeRF文章中的操作。
